### ISSUE TITLE
Chrome SSL Websockets

### ISSUE THREAD

**Issue by arenstar** [mrjoes/tornadio#10]
I dont understand why i am getting this error after switching to SSL..

Can anyone help???
im serving completely from a SSL enabled server.. :/

Error during WebSocket handshake: location mismatch: wss://dev.website.de/socket.io/websocket != ws://dev.website.de/socket.io/websocket

**Comment by statico** [comment]
FWIW, I've got a few lines that are something like:

```
var config = {
  secure: document.location.protocol == 'https:'
  ...
};
if (document.location.port === '443') {
  config.port = 443;
}
var socket = new io.socket(false, config);
```

The port logic is separate because I have different development, staging and production environments.

Maybe that helps.

**Comment by arenstar** [comment]
I have actually realised..
when im using 443..
document.location.port always equals nothing..
port: ""

hmmm.. any idea why?

**Comment by statico** [comment]
No, but maybe combining it with `document.location.protocol` could be of use.
