### ISSUE TITLE
Is there a way to access secure cookies from a SocketConnection?

### ISSUE THREAD

**Issue by chrelad** [mrjoes/tornadio#12]
Is there a way to get/set cookies from within a SocketConnection class? Since the secure cookie handling methods are a part of the RequestHandler object in Tornado, I'm not sure this is possible. When on_open is called, I see the encrypted secure cookie contents in the HTTPRequest object, but I'd like to operate on them using Tornado's get/set_secure_cookie methods so everything is consistent.

**Comment by kmike** [comment]
The actual RequestHandler subclass instance (e.g. TornadioWebSocketHandler instance) is available at Connection.on_open as 'self._protocol'. 

But cookies are not sent with all transports (e.g. with flash) so it not safe to rely on them. Please correct me if I'm wrong.

**Comment by kmike** [comment]
And it is not clear how setting cookies should work with websockets or flash.

**Comment by arenstar** [comment]
As a suggestion to how I implemented grabbing cookies.. ( however my implementation might be wrong )

From the Client side, on the initial connect passes a message (which passes the cookie)
I did it like this, as you can only guarantee the cookie to be correct on initial contact/connect, using websockets..
The self._protocol will be stale throughout the session.. So i didnt want to rely on it if the cookie was to be updated
This is not a problem with Socket.io but by implementation of building a websocket connection by specification..

Hope this helps

**Comment by chrelad** [comment]
Great, this is just what I was looking for. It is definitely important that there is a reliable means of passing cookie information back to the server when the websocket connection is established; luckily, we have some control at present over the browser that is used. In the short term, we'll go with the self._protocol method of retrieving the cookie information. Is Flash the only fallback that does not support sending cookie information when opening a new connection?

Thanks for the quick replies everyone!
