### ISSUE TITLE
FlashPolicyServer intermittent hangups

### ISSUE THREAD

**Issue by billychasen** [mrjoes/tornadio#15]
hey -- I've been debugging an issue where in firefox it sometimes reverts to xhr-polling instead of flashsocket.

It seems like the problem might be with the FlashPolicyServer, which sometimes returns the policy and other times disconnects after the client sends <policy-file-request/>

I'm able to repro as follows:

> telnet server 843
> Connected
> Escape character is '^]'.
> <policy-file-request/>
> Connection closed by foreign host.

**Comment by mrjoes** [comment]
Hi,

  Oh, that's probably because the following code, which does not assume 
that you can have line breaks:

if request != '<policy-file-request/>':

  So, I'd trim the string to fix the issue.

Edit: nevermind, it is reading exactly 22 bytes. Will have to debug.

**Comment by billychasen** [comment]
That's what I thought at first, but debug statements proved otherwise.

It would successfully get to that point and on its attempt to write back out, would get a thrown exception and the client would receive nothing.

**Comment by mrjoes** [comment]
I think I know what's going on. If you try to send to closed connection, it will throw exception. That's how Tornado works.

Not sure how to fix it - just suppress exception?

**Comment by billychasen** [comment]
Why would the connection be closing?  There is some other funkiness happening, because if I set up a simple tornado server to just reply with a flash policy file, it works fine.

**Comment by derekmcloughlin** [comment]
Hi,

When trying to simulate load on a Tornado/Tornadio chat server, I've noticed that asking for the flash policy XML document occasionally gives errors:

Simple script to ask for the policy document:

``` shell
while true
do
    python -c 'print "<policy-file-request/>%c" % 0' | nc 192.168.2.97 843
done
```

If you run one script in a shell it's fine. Run another instance of the script and you'll soon get errors:

```
10:04:14,400 ERROR [root] [MainThread] Exception in callback <tornado.stack_context._StackContextWrapper object at 0x26bc940>
Traceback (most recent call last):
  File "/home/derek/work/chat/CHAT/lib/python2.7/site-packages/tornado-2.0-py2.7.egg/tornado/ioloop.py", line 370, in _run_callback
    callback()
  File "/home/derek/work/chat/CHAT/lib/python2.7/site-packages/tornado-2.0-py2.7.egg/tornado/stack_context.py", line 159, in wrapped
    callback(*args, **kwargs)
  File "/home/derek/work/chat/CHAT/lib/python2.7/site-packages/tornado-2.0-py2.7.egg/tornado/iostream.py", line 235, in wrapper
    callback(*args)
  File "/home/derek/work/chat/CHAT/lib/python2.7/site-packages/tornado-2.0-py2.7.egg/tornado/stack_context.py", line 159, in wrapped
    callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/tornadio/flashserver.py", line 56, in _handle_request
    self.stream.write(file_handle.read() + '\0')
  File "/home/derek/work/chat/CHAT/lib/python2.7/site-packages/tornado-2.0-py2.7.egg/tornado/iostream.py", line 167, in write
    self._check_closed()
  File "/home/derek/work/chat/CHAT/lib/python2.7/site-packages/tornado-2.0-py2.7.egg/tornado/iostream.py", line 403, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
```

Does this have to be served by Tornadio or can it be served by any other process on the same server/port?

**Comment by derekmcloughlin** [comment]
I've answered my own question - you _can_ run the policy server from another process (e.g. as outlined in http://www.adobe.com/devnet/flashplayer/articles/socket_policy_files.html), just don't specify 'flash_policy_file' or 'flash_policy_port' when creating the tornado.web.Application object.

**Comment by mrjoes** [comment]
Closed for now, not reproducible on my end.
