### ISSUE TITLE
WebSocket ietf-hybi-07 support in Tornadio

### ISSUE THREAD

**Issue by ghost** [mrjoes/tornadio#17]
Hi!

I just noticed that Firefox 6 was just released, with WebSockets re-enabled.
It seems to support WebSockets protocol version draft-ietf-hybi-thewebsocketprotocol-07.
Would it be possible for Tornadio to also support this protocol version?

I'm using Tornadio in my project, http://www.freeciv.net/ and it seems to work very nicely so far. 
Good work!  :)

Andreas R.
www.freeciv.net

**Comment by mrjoes** [comment]
Will have to check with Tornado guys, as tornadio is reusing WebSocket support from Tornado. If they're not planning to add support for new draft, I might do it as a patch.

**Comment by mrjoes** [comment]
Closing it - Tornado guys added support for all flavors of websockets now. 
See https://github.com/facebook/tornado/commit/84d7b458f956727c3b0d6710b68050186ce01a35
