### ISSUE TITLE
Clean stop of the SocketServer

### ISSUE THREAD

**Issue by ljean** [mrjoes/tornadio#19]
Hello,
First of all, thank you very much tornadio. I like it very much.

I don't find a way to make a clean stop of the SocketServer. I would like to be able to start/stop/restart but i don't have access to the internal io_loop instance. Is it possible to make it accessible?

Is there a better way to make a clean stop?

Best
luc

**Comment by mrjoes** [comment]
If you don't explicitly pass io_loop instance to the tornadio, it will use default one from Tornado.

So, you can access io_loop by:
from tornado import ioloop
ioloop.IOLoop.instance()

Serge.

**Comment by ljean** [comment]
It works perfectly. Thanks.
