### ISSUE TITLE
Tornadio only supports Socket.IO < 0.7

### ISSUE THREAD

**Issue by pgebheim** [mrjoes/tornadio#22]
The recent changes to the Socket.IO protocol allow for some very nice features, but the protocol change was drastic enough to break Tornadio.

The newest protocol spec is being published at:
https://github.com/learnboost/socket.io-spec

Is there any work planned for bringing Tornadio up-to-date?

**Comment by mrjoes** [comment]
Yes, I'm going to support new version of the protocol, but it will require major rewrite of the current implementation due to all new features of 0.7. Didn't start it because 0.7 is not very stable yet.

I plan to do it as a separate project, this one will stay intact.

**Comment by christarnowski** [comment]
Socket.IO 0.8 is out (https://groups.google.com/forum/#!topic/socket_io/APIDEv0QehE), but stability-wise it's not quite there yet.

I like you work on TornadIO - I'm using it in one of my projects and it gets the job done. Well done! In fact, if you don't mind, I would like to help you out with the new project you've mentioned above. Let me know if you're interested!

Best,
Krzysztof.

**Comment by bergundy** [comment]
I'm also using tornadio in one of my projects and would really love to see it support socket.io 0.8.

Have you started implementing the new spec already?

Great job so far!

Contact me if you need any help.

**Comment by peterbe** [comment]
Just pseudo-trolling my added support MrJoes. I'll be around to help too.

**Comment by FranciscoTomeCosta** [comment]
Any updates on supporting socket.io v0.8x?

**Comment by mrjoes** [comment]
It is flashmob!

Sorry, was quite busy with other projects and will start implementation very soon. Hope to have alpha by end of the next week.

**Comment by almoutinho** [comment]
Any progress on supporting the latest version of socket.io?
The alpha you talked about is available for download?

**Comment by mrjoes** [comment]
Still working on it, takes longer that I expected.

**Comment by mrjoes** [comment]
Closing this one - there's Tornadio2 now, which supports 0.7+ transports.

Most of the features work, but it needs some additional testing. Check readme for more details.

**Comment by bergundy** [comment]
Thanks for this. Keep up the good work!

**Comment by FranciscoTomeCosta** [comment]
great work! thanks!
