### ISSUE TITLE
Resumable Sessions

### ISSUE THREAD

**Issue by spodkowinski** [mrjoes/tornadio#28]
I'm not sure if this is a bug, a feature request or if I'm just doing this wrong as I'm new to socket.io. What I'd like to do is use tornadio with xhr-polling to create some kind of chatroom like application. This is working fine so far except when a user just hits reload in his browser or simply closes / opens browser again. In that case I'd like to send him back automatically to his current channel. So I open a new socket.io connection for the previous channel after hes back. However, this will get me a new session ID and shortly after I can see the old session ID timing out and have me broadcasting a "member left" message although the member is still back in the channel.

Is there any way to specify a session Id on my own (e.g. by using a user ID) and make tornadio recognize it so I can really make sure that the same user will not have multiple sessions? I gave it a try by just hard coding the session_id value in the Session class but got very strange results.

**Comment by mrjoes** [comment]
Unfortunately, socket.io (and tornadio) does not support resumable sessions. Think of socket.io as a networking layer, nothing more.

It is up for you, as a developer, to authenticate client and send all queued messages. Best way to do this would be to have some token which uniquely identifies client and some kind of persistent storage (redis will be very good for this particular task).
