### ISSUE TITLE
Tornadio doesn't work in Tornado 2.1

### ISSUE THREAD

**Issue by equake** [mrjoes/tornadio#32]
Tornado fails with the following message: "AssertionError: groups in url regexes must either be all named or all positional"

See: http://groups.google.com/group/python-tornado/browse_thread/thread/7961f801955d03ad

Marcos

**Comment by mrjoes** [comment]
Which version of Tornadio do you use? This was fixed some time ago and it is working for me with Tornado 2.1.

Just in case, I deployed latest git version as 0.5, try updating.

**Comment by mrjoes** [comment]
I assume that it is working as expected.
