### ISSUE TITLE
Feature request: Add request to SocketConnection objects

### ISSUE THREAD

**Issue by statico** [mrjoes/tornadio#6]
It's be nice if `SocketConnection` had some sort of information about the connection — like the remote IP or transport type — so I could log it to the console.

**Comment by statico** [comment]
Actually, I see that a `protocol` keyword argument is passed to `on_open()` — got it. Remote IP would still be nice :)

**Comment by mrjoes** [comment]
Sure, I will transfer client IP, browser and other properties from the underlying connection.

**Comment by statico** [comment]
Awesome, thanks!

**Comment by the1plummie** [comment]
for persisten connections, you can get remote_ip from self._protocol.stream.socket.getpeername()
no idea how to dig that info for xhr-polling tho. :)

**Comment by arenstar** [comment]
I would love to see the headers come through.
I really need to clean my global storage where i put the client object..
mapping for example the id stored in a cookie..
so when the user arrives, i add it into the global dict, and when the user disconnects i remove it from the global dict.. since we now dont have session_ids either..

This makes things quite complicated compared to the old version, or the node implementation..

Its imperative that i can map my user/client object (aka self, to an ID ) :/

Is this possible?

**Comment by mrjoes** [comment]
There was some discussion here, about session_ids: https://github.com/MrJoes/tornadio/issues/closed#issue/8

Overall, your connection objects are unique and represent one connection from the user. If you absolutely want to have some kind of unique id for the user (as a replacement for session_id) - just generate guid in your on_open and store in your object.

As for the some kind of logical user persistence - sure, I can store request object from _first_ request that came for that session, so it will include incoming IP address, headers, browser version, etc. Means, if cookie was set on first request and was not in all subsequent, it will be still present.

Do you see any problems with this approach?

**Comment by arenstar** [comment]
I did read this post, i was actually quite interested in how i would store this id in the "self" object.. can you perhaps describe that to me??

Further, i think it would be great to have some information about the client connecting on the handler on_open.. ( i completely understand that this will not update on subsequent updates - as far as i can see, the user would need to close the connection and reopen it)

I could then, identify the user when he connects.. give him an id in the user object and when he leaves replay the id to my "backend" which tracks him..

Would this be complicated to implement? I would love to try this out. :D

**Comment by mrjoes** [comment]
Take a look: https://github.com/MrJoes/tornadio/commit/61fd3e57d73ec327a6e057ebc8453f5fbb4dc2e5

Overall, request will be passed to the on_open handler as one of the parameters. If you want to accept it, just add request as a first parameter. Also, changed ping sample to give example how to read remote_ip property from the passed request object.

As for the cookies - I don't know how you can send them back, especially for persistent transports. Will need to think about it.

**Comment by mrjoes** [comment]
arenstar: you can do something like::
      def on_open(_args, *_kwargs):  
         self.my_id = uuid.uuid1()

Then, you just work with self.my_id as usual. Basically, it is your user identifier.

**Comment by arenstar** [comment]
Well.. 

at first it works, but as it falls back from websockets too xhr-polling.. it freaks out

tornadio/pollingsession.py", line 46, in **init**

self.on_open(self.request, _args, *_kwargs)
    AttributeError: 'PollingSession' object has no attribute 'request'

Im really not sure why.. every tornado request should contain this :/

**Comment by mrjoes** [comment]
Sorry, you're right. Committed change in a hurry.

Polling transports are now fixed too.

**Comment by arenstar** [comment]
Fantastic :D
Thank you..

**Comment by statico** [comment]
I wanted simple integer IDs instead of UUIDs, so I did this:

```
class SocketHandler(tornadio.SocketConnection):
    _counter = 0

    def __init__(self, *args, **kwargs):
        super(SocketHandler, self).__init__(*args, **kwargs)

        with threading.Lock():
            self.__class__._counter += 1
            self.id = self.__class__._counter
```

I'm not sure if it's stupid or not...

**Comment by mrjoes** [comment]
It'll work just fine.

Btw, you don't have to use threading.Lock() - tornado is single-threaded.
