### ISSUE TITLE
on_close not called on firefox and opera

### ISSUE THREAD

**Issue by xigit** [mrjoes/tornadio#7]
Thanks for sharing this great library,

I have tested your chatroom example simultanously in three browser : chrome, opera and firefox.
It's work well until i noticed that if i close the app on opera and firefox, on_close function not called ( " A User has Left" not displayed), 
but if i closed the app on chrome, on_close function is called.
do you know what happened to it?

Thanks.

**Comment by mrjoes** [comment]
There's a problem with Opera and socket.io.

Here's more elaborate description: http://groups.google.com/group/socket_io/browse_thread/thread/9dc1013439d42ee2
